max_samples: 20000
coverage_threshold: 0.7
min_per_bin: 20
patch_variant: spectral
# exemples de paramètres additionnels (peuvent être étendus)
roll_shifts: [-64, -32, 0, 32, 64]
xor_seeds: [11, 29, 47, 83]
perm_rows_seeds: [3, 7, 13, 19]
perm_cols_seeds: [5, 17, 23, 31]
block_sizes: [8, 16, 32, 64]
block_seeds: [2, 5, 11]
